# menus.py

PACKS = {
    "patient": [
        {
            "id": "Patient_Dossier.py",
            "label": "Dossier Patient",
            "file": "Patient_Dossier.py",
            "icon": "📁",
            "description": "Consulter et modifier les informations du dossier",
        },
        {
            "id": "Patient_RendezVous.py",
            "label": "Rendez-vous",
            "file": "Patient_RendezVous.py",
            "icon": "📅",
            "description": "Voir et planifier les rendez-vous médicaux",
        },
        {
            "id": "Patient_CarnetSante.py",
            "label": "Carnet de Santé",
            "file": "Patient_CarnetSante.py",
            "icon": "🩺",
            "description": "Suivi personnel de la santé du patient",
        },
    ],
    "doctor": [
        {
            "id": "Doctors_Page.py",
            "label": "Accueil Médecin",
            "file": "Doctors_Page.py",
            "icon": "🩺",
            "description": "Vue d'ensemble du médecin",
        },
        {
            "id": "Doctor_Diagnosis.py",
            "label": "Diagnostic",
            "file": "Doctor_Diagnosis.py",
            "icon": "🔬",
            "description": "Saisir et consulter les diagnostics",
        },
        {
            "id": "Doctor_History.py",
            "label": "Historique",
            "file": "Doctor_History.py",
            "icon": "📚",
            "description": "Historique médical du patient",
        },
        {
            "id": "Doctor_Prescriptions.py",
            "label": "Prescriptions",
            "file": "Doctor_Prescriptions.py",
            "icon": "💊",
            "description": "Créer et gérer les ordonnances",
        },
        {
            "id": "Doctor_Consultation_Requests.py",
            "label": "Demandes de consultation",
            "file": "Doctor_Consultation_Requests.py",
            "icon": "📩",
            "description": "Voir les demandes en attente",
        },
    ],
    "midwife": [
        {
            "id": "Demographics.py",
            "label": "Démographie",
            "file": "Demographics.py",
            "icon": "👶",
            "description": "Informations démographiques des patientes",
        },
        {
            "id": "Prenatal_Care.py",
            "label": "Soins prénataux",
            "file": "Prenatal_Care.py",
            "icon": "🤰",
            "description": "Suivi des soins avant l'accouchement",
        },
        {
            "id": "Intrapartum_Care.py",
            "label": "Soins intrapartum",
            "file": "Intrapartum_Care.py",
            "icon": "🏥",
            "description": "Suivi pendant le travail et l'accouchement",
        },
        {
            "id": "Post_Natal_Care.py",
            "label": "Soins postnataux",
            "file": "Post_Natal_Care.py",
            "icon": "🍼",
            "description": "Suivi après l'accouchement",
        },
        {
            "id": "Throughout_Midwifery_Care.py",
            "label": "Suivi global",
            "file": "Throughout_Midwifery_Care.py",
            "icon": "📈",
            "description": "Vue d'ensemble du parcours de soins",
        },
    ],
    "nurse": [
        {
            "id": "Infirmiere_Patients.py",
            "label": "Patients",
            "file": "Infirmiere_Patients.py",
            "icon": "👩‍⚕️",
            "description": "Liste et suivi des patients",
        },
        {
            "id": "Infirmiere_Medicaments.py",
            "label": "Médicaments",
            "file": "Infirmiere_Medicaments.py",
            "icon": "💉",
            "description": "Gestion des traitements et prescriptions",
        },
    ],
    "organisation": [
        {
            "id": "Appointments_Calendar.py",
            "label": "Calendrier des rendez-vous",
            "file": "Appointments_Calendar.py",
            "icon": "🗓️",
            "description": "Vue globale des rendez-vous planifiés",
        },
        {
            "id": "Modify_Patient_Folder.py",
            "label": "Modifier dossier patient",
            "file": "Modify_Patient_Folder.py",
            "icon": "✏️",
            "description": "Accès administratif aux dossiers",
        },
    ],
    "messages": [
        {
            "id": "Inbox.py",
            "label": "Boîte de réception",
            "file": "Inbox.py",
            "icon": "📥",
            "description": "Voir les messages reçus",
        },
        {
            "id": "Chat.py",
            "label": "Chat",
            "file": "Chat.py",
            "icon": "💬",
            "description": "Messagerie instantanée",
        },
        {
            "id": "Send_Message.py",
            "label": "Envoyer un message",
            "file": "Send_Message.py",
            "icon": "📤",
            "description": "Composer et envoyer un nouveau message",
        },
        {
            "id": "Receive_Message.py",
            "label": "Recevoir un message",
            "file": "Receive_Message.py",
            "icon": "📨",
            "description": "Réception et affichage des messages",
        },
    ],
    "admin": [
        {
            "id": "Admin_Logs.py",
            "label": "Logs système",
            "file": "Admin_Logs.py",
            "icon": "🧾",
            "description": "Historique des actions et événements",
        },
        {
            "id": "Admin_Roles.py",
            "label": "Rôles",
            "file": "Admin_Roles.py",
            "icon": "🛡️",
            "description": "Gestion des rôles et permissions",
        },
        {
            "id": "Admin_Users.py",
            "label": "Utilisateurs",
            "file": "Admin_Users.py",
            "icon": "👥",
            "description": "Liste et gestion des comptes",
        },
        {
            "id": "Admin_Settings.py",
            "label": "Paramètres",
            "file": "Admin_Settings.py",
            "icon": "⚙️",
            "description": "Configuration du système",
        },
    ],
}
