# 🧭 Suggestions de Menu Générées Automatiquement
# Date : 16 Oct 2025, 04:14

menu_suggestions = {
    "student": [
        {
            "label": "Academic Tracking",
            "icon": "📚",
            "module": "form_academic_tracking",
        },
        {"label": "Courses", "icon": "📚", "module": "form_courses"},
        {"label": "Evaluations", "icon": "📚", "module": "form_evaluations"},
        {
            "label": "Student Dashboard",
            "icon": "📚",
            "module": "form_student_dashboard",
        },
    ],
    "admin": [
        {
            "label": "Admin Audit Dashboard",
            "icon": "🛠️",
            "module": "form_admin_audit_dashboard",
        },
        {"label": "Admin Dashboard", "icon": "🛠️", "module": "form_admin_dashboard"},
        {
            "label": "Admin Dashboard Modules",
            "icon": "🛠️",
            "module": "form_admin_dashboard_modules",
        },
        {"label": "Admin Data", "icon": "🛠️", "module": "form_admin_data"},
        {"label": "Admin Hashing", "icon": "🛠️", "module": "form_admin_hashing"},
        {"label": "Admin Logs", "icon": "🛠️", "module": "form_admin_logs"},
        {
            "label": "Admin Module Manager",
            "icon": "🛠️",
            "module": "form_admin_module_manager",
        },
        {"label": "Admin Roles", "icon": "🛠️", "module": "form_admin_roles"},
        {"label": "Admin Users", "icon": "🛠️", "module": "form_admin_users"},
        {"label": "Editor Admin", "icon": "🛠️", "module": "form_editor_admin"},
    ],
    "patient": [
        {"label": "Appointments", "icon": "🧍", "module": "form_appointments"},
        {"label": "Patient", "icon": "🧍", "module": "form_patient"},
        {
            "label": "Patient Dashboard",
            "icon": "🧍",
            "module": "form_patient_dashboard",
        },
        {"label": "Patient Data", "icon": "🧍", "module": "form_patient_data"},
        {"label": "Patient File", "icon": "🧍", "module": "form_patient_file"},
        {"label": "Patient History", "icon": "🧍", "module": "form_patient_history"},
        {
            "label": "Patient Monitoring",
            "icon": "🧍",
            "module": "form_patient_monitoring",
        },
        {"label": "Patients Alerts", "icon": "🧍", "module": "form_patients_alerts"},
        {"label": "Prescription", "icon": "🧍", "module": "form_prescription"},
        {"label": "Visit History", "icon": "🧍", "module": "form_visit_history"},
    ],
    "shared": [
        {"label": "Audit Simulated", "icon": "🗂️", "module": "form_audit_simulated"},
        {"label": "Book Appointment", "icon": "🗂️", "module": "form_book_appointment"},
        {"label": "Calendar", "icon": "🗂️", "module": "form_calendar"},
        {"label": "Config System", "icon": "🗂️", "module": "form_config_system"},
        {
            "label": "Consultation Requests",
            "icon": "🗂️",
            "module": "form_consultation_requests",
        },
        {"label": "Contact Info", "icon": "🗂️", "module": "form_contact_info"},
        {"label": "Create", "icon": "🗂️", "module": "form_create"},
        {"label": "Daily Care", "icon": "🗂️", "module": "form_daily_care"},
        {"label": "Daily Tasks", "icon": "🗂️", "module": "form_daily_tasks"},
        {"label": "Dashboard", "icon": "🗂️", "module": "form_dashboard"},
        {"label": "Demographics", "icon": "🗂️", "module": "form_demographics"},
        {"label": "Diagnostic", "icon": "🗂️", "module": "form_diagnostic"},
        {
            "label": "Due Date Calculator",
            "icon": "🗂️",
            "module": "form_due_date_calculator",
        },
        {
            "label": "Emotional Well Being",
            "icon": "🗂️",
            "module": "form_emotional_well_being",
        },
        {"label": "Export Pdf", "icon": "🗂️", "module": "form_export_pdf"},
        {"label": "Feedback", "icon": "🗂️", "module": "form_feedback"},
        {"label": "Follow Up", "icon": "🗂️", "module": "form_follow_up"},
        {"label": "Group Management", "icon": "🗂️", "module": "form_group_management"},
        {"label": "Hashing", "icon": "🗂️", "module": "form_hashing"},
        {"label": "Home", "icon": "🗂️", "module": "form_home"},
        {"label": "Log Deleter", "icon": "🗂️", "module": "form_log_deleter"},
        {"label": "Login", "icon": "🗂️", "module": "form_login"},
        {"label": "Logs", "icon": "🗂️", "module": "form_logs"},
        {"label": "Medical Agenda", "icon": "🗂️", "module": "form_medical_agenda"},
        {"label": "Medical Notes", "icon": "🗂️", "module": "form_medical_notes"},
        {"label": "Messages", "icon": "🗂️", "module": "form_messages"},
        {"label": "Notifications", "icon": "🗂️", "module": "form_notifications"},
        {"label": "Nutrition", "icon": "🗂️", "module": "form_nutrition"},
        {"label": "Pack Organisation", "icon": "🗂️", "module": "form_pack_organisation"},
        {"label": "Page", "icon": "🗂️", "module": "form_page"},
        {"label": "Profile", "icon": "🗂️", "module": "form_profile"},
        {"label": "Qui Sommes Nous", "icon": "🗂️", "module": "form_qui_sommes_nous"},
        {"label": "Report Dashboard", "icon": "🗂️", "module": "form_report_dashboard"},
        {"label": "Resources", "icon": "🗂️", "module": "form_resources"},
        {"label": "Results", "icon": "🗂️", "module": "form_results"},
        {"label": "Role Navigator", "icon": "🗂️", "module": "form_role_navigator"},
        {"label": "Self Report", "icon": "🗂️", "module": "form_self_report"},
        {"label": "Settings", "icon": "🗂️", "module": "form_settings"},
        {"label": "Stats", "icon": "🗂️", "module": "form_stats"},
        {"label": "Supervision", "icon": "🗂️", "module": "form_supervision"},
        {"label": "Supply", "icon": "🗂️", "module": "form_supply"},
        {"label": "Supply Request", "icon": "🗂️", "module": "form_supply_request"},
        {"label": "Update", "icon": "🗂️", "module": "form_update"},
        {"label": "User Management", "icon": "🗂️", "module": "form_user_management"},
        {
            "label": "User Management Supabase",
            "icon": "🗂️",
            "module": "form_user_management_supabase",
        },
        {
            "label": "Validator Dashboard",
            "icon": "🗂️",
            "module": "form_validator_dashboard",
        },
        {"label": "View Notes", "icon": "🗂️", "module": "form_view_notes"},
        {"label": "View Records", "icon": "🗂️", "module": "form_view_records"},
        {"label": "Workshops", "icon": "🗂️", "module": "form_workshops"},
    ],
    "midwife": [
        {"label": "Birth Plan", "icon": "🍼", "module": "form_birth_plan"},
        {"label": "Childbirth", "icon": "🍼", "module": "form_childbirth"},
        {
            "label": "Consultation Midwife",
            "icon": "🍼",
            "module": "form_consultation_midwife",
        },
        {"label": "Delivery Log", "icon": "🍼", "module": "form_delivery_log"},
        {
            "label": "Education Prevention",
            "icon": "🍼",
            "module": "form_education_prevention",
        },
        {
            "label": "Initial Anamnesis",
            "icon": "🍼",
            "module": "form_initial_anamnesis",
        },
        {"label": "Initial Exam", "icon": "🍼", "module": "form_initial_exam"},
        {"label": "Intrapartum Care", "icon": "🍼", "module": "form_intrapartum_care"},
        {"label": "Midwife", "icon": "🍼", "module": "form_midwife"},
        {
            "label": "Midwife Dashboard",
            "icon": "🍼",
            "module": "form_midwife_dashboard",
        },
        {"label": "Postnatal Care", "icon": "🍼", "module": "form_postnatal_care"},
        {
            "label": "Pregnancy Tracking",
            "icon": "🍼",
            "module": "form_pregnancy_tracking",
        },
        {"label": "Prenatal Care", "icon": "🍼", "module": "form_prenatal_care"},
        {
            "label": "Throughout Midwifery Care",
            "icon": "🍼",
            "module": "form_throughout_midwifery_care",
        },
    ],
    "doctor": [
        {"label": "Contact Doctor", "icon": "🩺", "module": "form_contact_doctor"},
        {"label": "Doctor Dashboard", "icon": "🩺", "module": "form_doctor_dashboard"},
        {
            "label": "Doctoral Dashboard",
            "icon": "🩺",
            "module": "form_doctoral_dashboard",
        },
    ],
    "guest": [
        {"label": "Guest", "icon": "👤", "module": "form_guest"},
        {"label": "Guest Dashboard", "icon": "👤", "module": "form_guest_dashboard"},
    ],
    "intern": [
        {"label": "Intern Dashboard", "icon": "🧪", "module": "form_intern_dashboard"},
        {"label": "Intern Logbook", "icon": "🧪", "module": "form_intern_logbook"},
        {
            "label": "Internship Request",
            "icon": "🧪",
            "module": "form_internship_request",
        },
    ],
    "nurse": [
        {
            "label": "Medication Management",
            "icon": "💉",
            "module": "form_medication_management",
        },
        {"label": "Nurse Dashboard", "icon": "💉", "module": "form_nurse_dashboard"},
        {"label": "Nursing Notes", "icon": "💉", "module": "form_nursing_notes"},
        {"label": "Nursing Reports", "icon": "💉", "module": "form_nursing_reports"},
        {"label": "Schedule Nurse", "icon": "💉", "module": "form_schedule_nurse"},
        {"label": "Vital Signs", "icon": "💉", "module": "form_vital_signs"},
    ],
    "doctoral": [
        {"label": "Publications", "icon": "🎓", "module": "form_publications"},
        {"label": "Research Project", "icon": "🎓", "module": "form_research_project"},
        {"label": "Thesis Tracking", "icon": "🎓", "module": "form_thesis_tracking"},
    ],
}
